/********************************************************************************
 *    Project   : Awesomium.Chromium.Tabs
 *    File      : Enums.cs
 *    Version   : 1.0.1.0 
 *    Date      : 6/7/2013
 *    Author    : Perikles C. Stephanidis (perikles@amadeusoft.com)
 *    Copyright : ©2013 Amadeus Software SRL    
 *-------------------------------------------------------------------------------
 *
 *    Notes     :
 *
 *    Includes enumerations used by the project, that are not automatically
 *    generated by the bmac generator.
 *    
 *    
 ********************************************************************************/

using System;

namespace Amadeus.Chromium.Tabs 
{
    public enum CTBrowserCommand {
        CTBrowserCommandNewWindow                 = 34000,
        CTBrowserCommandNewIncognitoWindow        = 34001,
        CTBrowserCommandCloseWindow               = 34012,
        CTBrowserCommandAlwaysOnTop               = 34013,
        CTBrowserCommandNewTab                    = 34014,
        CTBrowserCommandCloseTab                  = 34015,
        CTBrowserCommandSelectNextTab             = 34016,
        CTBrowserCommandSelectPreviousTab         = 34017,
        CTBrowserCommandSelectTab0                = 34018,
        CTBrowserCommandSelectTab1                = 34019,
        CTBrowserCommandSelectTab2                = 34020,
        CTBrowserCommandSelectTab3                = 34021,
        CTBrowserCommandSelectTab4                = 34022,
        CTBrowserCommandSelectTab5                = 34023,
        CTBrowserCommandSelectTab6                = 34024,
        CTBrowserCommandSelectTab7                = 34025,
        CTBrowserCommandSelectLastTab             = 34026,
        CTBrowserCommandDuplicateTab              = 34027,
        CTBrowserCommandRestoreTab                = 34028,
        CTBrowserCommandShowAsTab                 = 34029,
        CTBrowserCommandFullscreen                = 34030,
        CTBrowserCommandExit                      = 34031,
        CTBrowserCommandMoveTabNext               = 34032,
        CTBrowserCommandMoveTabPrevious           = 34033
    }

    public enum CTWindowOpenDisposition {
        CTWindowOpenDispositionCurrentTab,
        CTWindowOpenDispositionNewForegroundTab,
        CTWindowOpenDispositionNewBackgroundTab,
    }
}
